### ISSUE TITLE
Expression with logical operators and relations

### ISSUE THREAD

**Issue by scmu** [scmlab/gcl#16]
Opening `examples/gcd.gcl`, we get the type error "Cannot unify: Bool with : Int":

![Screen Shot 2021-03-14 at 5 00 28 PM](https://user-images.githubusercontent.com/11384501/111062904-d8d34100-84e6-11eb-9afb-e06386824044.jpg)

Adding parentheses around `A > 0` and `B > 0` (that is, `(A > 0) ∧ (B > 0)`) resolves the problem, for a while I guess it is a parsing error: logical operators (e.g. (∧)) should bind looser than relations. 

However, omitting the type error, I also get the funny looking global property `A > 0 ∧ (0 ∧ B > 0)`:

![Screen Shot 2021-03-14 at 5 06 45 PM](https://user-images.githubusercontent.com/11384501/111063092-cdcce080-84e7-11eb-904a-c92fbe092a89.jpg)

It might be the case that there is something weird going on within the parser.

**Comment by potsrevennil** [comment]
Modified the precedence of connection and disjunction. The issue should be fixed.

**Comment by scmu** [comment]
On my machine here the issue still persists. I get a different global property `A > (0 ∧ B) ∧ (0 ∧ B) > 0`, however.

![Screen Shot 2021-03-15 at 12 50 25 AM](https://user-images.githubusercontent.com/11384501/111076729-7864f380-8528-11eb-95a7-2c93a65d607f.jpg)

**Comment by potsrevennil** [comment]
Should be the issue of how to interpret the `Chain` constructor.

**Comment by potsrevennil** [comment]
Pushed to master, the issue should be fixed.

**Comment by potsrevennil** [comment]
Pushed to master branch, the issue should be fixed.
